server:
  port: 8080
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

